spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example_database?currentSchema=task_list
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never #always
      continue-on-error: false
