spring:
  config:
    import: optional:file:.env[.properties]
#  cache:
#    type: redis
#    cache-names: redis-cache
#  data:
#    redis:
#      host: ${SPRING_DATA_REDIS_HOST}
#      port: ${SPRING_DATA_REDIS_PORT}
#      database: ${SPRING_DATA_REDIS_DATABASE}
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:5432/example_database?currentSchema=task_list
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: task_list
  graphql:
    graphiql:
      enabled: true
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  jpa:
    open-in-view: false

jwt:
 token:
  secret: ${JWT_TOKEN_SECRET}
  expired: ${JWT_TOKEN_EXPIRED}

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

springdoc:
  override-with-generic-response: false